- name: apt-get update
  apt:
    update_cache: yes
  become: yes

- name: Ensure that zip and unzip are installed
  apt:
    pkg:
      - zip
      - unzip
    state: present
  become: yes

- name: Ensure that the consul package {{ consul_download_url }} is dowloaded to {{ consul_installation_path }}
  get_url:
    url: "{{ consul_download_url }}"
    dest: "{{ consul_installation_path }}"
    sha256sum: "{{ consul_sha256_checksum }}"

- name: Extract the consul package {{ consul_installation_path }} to /usr/bin
  unarchive:
    src: "{{ consul_installation_path }}"
    dest: "/usr/bin"
    remote_src: yes
  become: yes

- name: Ensure that {{ consul_config_path }} exists
  file:
    path: "{{ consul_config_path }}"
    state: directory

- name: Ensure that {{ consul_var_path }} exists
  file:
    path: "{{ consul_data_path }}"
    state: directory

- name: Copy the config-{{ consul_mode }}.json.j2 into "{{ consul_config_path }}/config.json"
  template:
    src: config-{{ consul_mode }}.json.j2
    dest: "{{ consul_config_path }}/config.json"

- name: Copy the cloud_auto_join_{{ consul_cloud_provider }}.json.j2 into "{{ consul_config_path }}/cloud_auto_join.json"
  template:
    src: "cloud_auto_join_{{ consul_cloud_provider }}.json.j2"
    dest: "{{ consul_config_path }}/cloud_auto_join.json"

- name: Copy the consul.service.j2 into /etc/systemd/system/consul.service
  template:
    src: consul.service.j2
    dest: /etc/systemd/system/consul.service

- name: Ensure that the consul.service is restarted
  systemd:
    name: consul.service
    enabled: yes
